### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [JakeWharton/flip-tables#10]
Hi
All java source files are without license headers.
Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by JakeWharton** [comment]
I have added license headers to match the applied license in the readme as 48e45f1b4ac8096fa5107dbc0d622bbb85148d9f
