### ISSUE TITLE
FlipTableConverters.fromResultSet() is not public

### ISSUE THREAD

**Issue by lex-divert** [JakeWharton/flip-tables#11]
flip-tables/src/main/java/com/jakewharton/fliptables/FlipTableConverters.java : line 100

The method signature doesn't include keyword "public", so calling it from another class raises a warning.

I'm using this in a Groovy-based test so it doesn't really matter, but it would make it harder to use in something more serious.

Happy to submit a pull request if it's useful, but first wanted to check whether it's intentional or I'm otherwise missing something.

Thanks for the tool! Otherwise works great and is totally saving me time in producing debug output.

**Comment by JakeWharton** [comment]
Yep this looks like a simple oversight on my part. I'd happily take a PR for it and can make a release shortly thereafter.

**Comment by jeremybrooks** [comment]
Submitted a pull request. Wanted to contribute something to this AWESOME project.
