### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by bitsofinfo** [JakeWharton/flip-tables#16]
Is this project dead?

Support questions and PRs are just sitting there. Should we fork this project or can it be maintained?

**Comment by JakeWharton** [comment]
Well it's stable and of extremely low importance to me.

**Comment by MitchTalmadge** [comment]
@bitsofinfo I will continue maintaining this project by merging it into my ASCIIGraph library, now renamed to ASCII-Data. 

https://github.com/MitchTalmadge/ASCII-Data

Give me a few days to port the code over and re-format it. :)

**Comment by bitsofinfo** [comment]
@MitchTalmadge in your replacement project for this, did you include the PR #15 ?

**Comment by MitchTalmadge** [comment]
@bitsofinfo Whoops, thanks for reminding me, I will get that in as soon as I get a chance!

**Comment by MitchTalmadge** [comment]
@bitsofinfo https://github.com/MitchTalmadge/ASCII-Data/releases/tag/1.2.0 I've included this in my port of this project. Will document it soon.

**Comment by MitchTalmadge** [comment]
Ok, documentation done in the wiki. Let me know if this looks good to you! Please start an issue on my own repository if you'd like to discuss it further :)

**Comment by bitsofinfo** [comment]
awesome, thanks man!
