### ISSUE TITLE
FlipTableConverters#fromResultSet is not public

### ISSUE THREAD

**Issue by sniffertine** [JakeWharton/flip-tables#22]

**Comment by JakeWharton** [comment]
Dupe of #11. What you're actually asking for is a release! Let me do that, instead.

**Comment by sniffertine** [comment]
indeed. sorry for dupping

**Comment by JakeWharton** [comment]
No problem! I have _clearly_ dropped the ball on getting a new release out.

**Comment by JakeWharton** [comment]
Released as 1.1.0. Should be available on Maven central in an hour.
