### ISSUE TITLE
Column length is not correctly calculated if the strings contain ANSI color escape codes.

### ISSUE THREAD

**Issue by metabrain** [JakeWharton/flip-tables#9]
Since they don't actually take space on the screen, it causes the String::length to mismatch the size the String takes up on the screen which causes severe misalignment issues.

I wouldn't mind to fix this on the weekend and submit a pull request, should be an easy fix.

**Comment by JakeWharton** [comment]
Please do! That would be great.

**Comment by metabrain** [comment]
No worries, cheers!

**Comment by metabrain** [comment]
I'll try to pick it up this weekend.
